version: '3.8'

services:
  dataset-build:
    build:
      context: .
      dockerfile: ./docker/tensorflow/Dockerfile
      args:
        WANDB_API_KEY: ${WANDB_API_KEY}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./docker/tensorflow/entrypoints/build_dataset.sh:/app/entrypoint.sh
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: [ "/app/entrypoint.sh" ]

  tensorflow:
    build:
      context: .
      dockerfile: ./docker/tensorflow/Dockerfile
      args:
        WANDB_API_KEY: ${WANDB_API_KEY}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./docker/tuning/entrypoint.sh:/app/entrypoint.sh
      - ./scripts:/app/scripts
      - ./data/processed:/app/data
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    runtime: nvidia
    shm_size: '10.08gb'
    command: [ "/app/entrypoint.sh" ]

  pytorch-n:
    build:
      context: .
      dockerfile: ./docker/pytorch-compose/Dockerfile
      args:
        WANDB_API_KEY: ${WANDB_API_KEY}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./docker/pytorch-compose/entrypoint.sh:/app/entrypoint.sh
      - ./scripts:/app/scripts
      - ./data/processed:/app/data
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    runtime: nvidia
    shm_size: '10.08gb'
    command: [ "/app/entrypoint.sh" ]

  jupyter:
    build:
      context: .
      dockerfile: ./docker/pytorch-compose/Dockerfile
      args:
        WANDB_API_KEY: ${WANDB_API_KEY}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    runtime: nvidia
    command:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/workspace"
      ]
