version: '3.8'

services:
  tensorflow-service:
    build:
      context: .
      dockerfile: ./docker/tensorflow/Dockerfile
      args:
        WANDB_API_KEY: ${WANDB_API_KEY}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    runtime: nvidia
    volumes:
      - .:/workspace

  dataset-build:
    extends:
      service: tensorflow-service
    volumes:
      - ./docker/tensorflow/entrypoints/build_dataset.sh:/app/entrypoint.sh
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: [ "/app/entrypoint.sh" ]

  tuning:
    extends:
      service: tensorflow-service
    volumes:
      - ./docker/tensorflow/entrypoints/tuning.sh:/app/entrypoint.sh
      - ./scripts:/app/scripts
      - ./data/processed:/app/data
    command: [ "/app/entrypoint.sh" ]

  jupyter-tf:
    extends:
      service: tensorflow-service
    ports:
      - "8888:8888"
    command:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/workspace"
      ]
